FROM node:14.16.1-slim

WORKDIR /app

COPY package.json /app

RUN apt-get update && \
    apt-get install -y fish git && \
    rm -rf /var/lib/apt/lists/* && \
    sed -i 's|/bin/bash|/usr/bin/fish|g' /etc/passwd && \
    npm install && \
    npm cache clean --force

EXPOSE 5000

COPY start.sh /

ENTRYPOINT ["/bin/bash", "/start.sh"]